# Generated by Django 2.2 on 2023-01-02 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('algorithm', models.CharField(choices=[('SumBasic', 'SumBasic'), ('LexRank', 'LexRank'), ('LSA', 'LSA'), ('TextRank', 'TextRank'), ('KLSum', 'KLSum'), ('GA', 'Genetic Algorithm'), ('SE', 'Search Economics')], max_length=50)),
                ('compression_rate', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('index', models.CharField(choices=[('ROUGE', 'ROUGE'), ('Cosine Similarity', 'Cosine Similarity'), ('F-measure', 'F-measure'), ('Bleu', 'Bleu')], max_length=50)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Summary')),
            ],
        ),
    ]
