# Generated by Django 2.2 on 2023-01-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(default='-'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
